### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by Cio425** [XPerson5467/BlushHandX#1]
I've downloaded the .exe file but all that's popping up whenever I click it is what's shown in the attached pi
![Screenshot (130)](https://user-images.githubusercontent.com/102626829/160714586-c4b1d21f-57ff-4749-a538-92924776d042.png)
c

**Comment by XPerson5467** [comment]
I forgot to include the pck file with the exe export. My apologies.
Reuploaded a zip that contains both files, download that.
